Repository PotatoMeme/nb_pitta_sns_app, pull requests merged in 2023-08, with the labels that each got.

#5 Feature/mainpage
  PittaSNSApp/.idea/deploymentTargetDropDown.xml
  PittaSNSApp/.idea/gradle.xml
  PittaSNSApp/.idea/misc.xml
  PittaSNSApp/app/build.gradle
  PittaSNSApp/app/src/main/AndroidManifest.xml
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/HomeFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/Key.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/MainActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SampleData.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SearchFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SettingFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/UserFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/adapter/PostRecyclerViewAdapter.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/adapter/ProfileRecyclerViewAdapter.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/model/Post.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/model/User.kt
  PittaSNSApp/app/src/main/res/anim/none.xml
  PittaSNSApp/app/src/main/res/anim/slide_in_right.xml
  PittaSNSApp/app/src/main/res/anim/slide_out_left.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_home_24.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_person_pin_24.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_search_24.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_settings_24.xml
  PittaSNSApp/app/src/main/res/drawable/bottom_background.xml
  PittaSNSApp/app/src/main/res/drawable/circle.xml
  PittaSNSApp/app/src/main/res/drawable/item_selector.xml
  PittaSNSApp/app/src/main/res/drawable/lavender_border.xml
  PittaSNSApp/app/src/main/res/drawable/sample_img.jpg
  PittaSNSApp/app/src/main/res/layout/activity_main.xml
  PittaSNSApp/app/src/main/res/layout/fragment_home.xml
  PittaSNSApp/app/src/main/res/layout/fragment_search.xml
  PittaSNSApp/app/src/main/res/layout/fragment_setting.xml
  PittaSNSApp/app/src/main/res/layout/fragment_user.xml
  PittaSNSApp/app/src/main/res/layout/item_post.xml
  PittaSNSApp/app/src/main/res/layout/item_profile.xml
  PittaSNSApp/app/src/main/res/menu/bottom_memu.xml
  PittaSNSApp/app/src/main/res/values-night/themes.xml
  PittaSNSApp/app/src/main/res/values/colors.xml
  PittaSNSApp/app/src/main/res/values/strings.xml
  PittaSNSApp/app/src/main/res/values/style.xml
  PittaSNSApp/app/src/main/res/values/themes.xml
Labels: feature ⚙️

#6 Feature/userdetail
  PittaSNSApp/.idea/gradle.xml
  PittaSNSApp/.idea/misc.xml
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/UserDetailActivity.kt
  PittaSNSApp/app/src/main/res/drawable/dudulogo.png
  PittaSNSApp/app/src/main/res/drawable/dudulogo2.png
  PittaSNSApp/app/src/main/res/drawable/dudulogo3.png
  PittaSNSApp/app/src/main/res/layout/activity_user_detail.xml
  PittaSNSApp/app/src/main/res/values/strings.xml
Labels: feature ⚙️

#7 Feature/post
  PittaSNSApp/app/src/main/res/drawable/back.jpg
  PittaSNSApp/app/src/main/res/drawable/pitta.jpg
  PittaSNSApp/app/src/main/res/drawable/pug.png
  PittaSNSApp/app/src/main/res/drawable/window.jpg
  PittaSNSApp/app/src/main/res/layout/activity_post_detail.xml
Labels: feature ⚙️

#8 Featur/toatl detail
  PittaSNSApp/app/build.gradle
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/MainActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostDetailActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SampleData.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/UserDetailActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/UserFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/adapter/StaggeredPostRecyclerViewAdapter.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/model/User.kt
  PittaSNSApp/app/src/main/res/anim/slide_in_right.xml
  PittaSNSApp/app/src/main/res/anim/slide_out_left.xml
  PittaSNSApp/app/src/main/res/layout/activity_post_detail.xml
  PittaSNSApp/app/src/main/res/layout/activity_user_detail.xml
  PittaSNSApp/app/src/main/res/layout/fragment_user.xml
  PittaSNSApp/app/src/main/res/layout/item_staggered_post.xml
Labels: feature ⚙️

#3 Feature/signup
  PittaSNSApp/app/build.gradle
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SignInActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SignUpActivity.kt
  PittaSNSApp/app/src/main/res/layout/activity_sign_in.xml
  PittaSNSApp/app/src/main/res/layout/activity_sign_up.xml
  PittaSNSApp/app/src/main/res/values/strings.xml
  PittaSNSApp/app/src/main/res/values/themes.xml
Labels: feature ⚙️

#9 Feature/total login
  PittaSNSApp/.idea/misc.xml
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostDetailActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SampleData.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SignInActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SignUpActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/Util.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/model/User.kt
  PittaSNSApp/app/src/main/res/drawable/back.jpg
  PittaSNSApp/app/src/main/res/drawable/dudulogo.png
  PittaSNSApp/app/src/main/res/drawable/dudulogo2.png
  PittaSNSApp/app/src/main/res/drawable/dudulogo3.png
  PittaSNSApp/app/src/main/res/drawable/pitta.jpg
  PittaSNSApp/app/src/main/res/drawable/pug.png
  PittaSNSApp/app/src/main/res/drawable/window.jpg
  PittaSNSApp/app/src/main/res/layout/activity_sign_in.xml
  PittaSNSApp/app/src/main/res/layout/activity_sign_up.xml
  PittaSNSApp/app/src/main/res/layout/item_post.xml
Labels: feature ⚙️, fix 🔧, refactor ♻️

#10 Dev
  PittaSNSApp/.idea/deploymentTargetDropDown.xml
  PittaSNSApp/.idea/gradle.xml
  PittaSNSApp/.idea/misc.xml
  PittaSNSApp/app/build.gradle
  PittaSNSApp/app/src/main/AndroidManifest.xml
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/HomeFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/Key.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/MainActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostDetailActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SampleData.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SearchFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SettingFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SignInActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SignUpActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/UserDetailActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/UserFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/Util.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/adapter/PostRecyclerViewAdapter.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/adapter/ProfileRecyclerViewAdapter.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/adapter/StaggeredPostRecyclerViewAdapter.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/model/Post.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/model/User.kt
  PittaSNSApp/app/src/main/res/anim/none.xml
  PittaSNSApp/app/src/main/res/anim/slide_in_right.xml
  PittaSNSApp/app/src/main/res/anim/slide_out_left.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_home_24.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_person_pin_24.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_search_24.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_settings_24.xml
  PittaSNSApp/app/src/main/res/drawable/bottom_background.xml
  PittaSNSApp/app/src/main/res/drawable/circle.xml
  PittaSNSApp/app/src/main/res/drawable/item_selector.xml
  PittaSNSApp/app/src/main/res/drawable/lavender_border.xml
  PittaSNSApp/app/src/main/res/drawable/sample_img.jpg
  PittaSNSApp/app/src/main/res/layout/activity_main.xml
  PittaSNSApp/app/src/main/res/layout/activity_post_detail.xml
  PittaSNSApp/app/src/main/res/layout/activity_sign_in.xml
  PittaSNSApp/app/src/main/res/layout/activity_sign_up.xml
  PittaSNSApp/app/src/main/res/layout/activity_user_detail.xml
  PittaSNSApp/app/src/main/res/layout/fragment_home.xml
  PittaSNSApp/app/src/main/res/layout/fragment_search.xml
  PittaSNSApp/app/src/main/res/layout/fragment_setting.xml
  PittaSNSApp/app/src/main/res/layout/fragment_user.xml
  PittaSNSApp/app/src/main/res/layout/item_post.xml
  PittaSNSApp/app/src/main/res/layout/item_profile.xml
  PittaSNSApp/app/src/main/res/layout/item_staggered_post.xml
  PittaSNSApp/app/src/main/res/menu/bottom_memu.xml
  PittaSNSApp/app/src/main/res/values-night/themes.xml
  PittaSNSApp/app/src/main/res/values/colors.xml
  PittaSNSApp/app/src/main/res/values/strings.xml
  PittaSNSApp/app/src/main/res/values/style.xml
  PittaSNSApp/app/src/main/res/values/themes.xml
Labels: merge ✅

#11 Feature/post create update delete
  PittaSNSApp/app/src/main/AndroidManifest.xml
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/HomeFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/Key.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/MainActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostAddActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostDetailActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostUpdateActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SampleData.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SearchFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/UserDetailActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/UserFragment.kt
  PittaSNSApp/app/src/main/res/drawable/baseline_add_24.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_delete_24.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_edit_24.xml
  PittaSNSApp/app/src/main/res/layout/activity_main.xml
  PittaSNSApp/app/src/main/res/layout/activity_post_add.xml
  PittaSNSApp/app/src/main/res/layout/activity_post_update.xml
  PittaSNSApp/app/src/main/res/layout/activity_user_detail.xml
  PittaSNSApp/app/src/main/res/layout/fragment_user.xml
  PittaSNSApp/app/src/main/res/menu/bottom_memu.xml
  PittaSNSApp/app/src/main/res/menu/toolbar_menu.xml
Labels: feature ⚙️, fix 🔧

#13 signin,singup translate
  PittaSNSApp/.idea/gradle.xml
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SignInActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SignUpActivity.kt
  PittaSNSApp/app/src/main/res/layout/activity_sign_in.xml
  PittaSNSApp/app/src/main/res/layout/activity_sign_up.xml
  PittaSNSApp/app/src/main/res/values-en-rUS/strings.xml
  PittaSNSApp/app/src/main/res/values/strings.xml
Labels: feature ⚙️

#14 [REFACTOR] : ♻️ Translate other string value
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/MainActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostAddActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostDetailActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostUpdateActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SearchFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SettingFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SignInActivity.kt
  PittaSNSApp/app/src/main/res/layout/activity_post_add.xml
  PittaSNSApp/app/src/main/res/layout/activity_post_detail.xml
  PittaSNSApp/app/src/main/res/layout/activity_post_update.xml
  PittaSNSApp/app/src/main/res/values-en-rUS/strings.xml
  PittaSNSApp/app/src/main/res/values/strings.xml
Labels: refactor ♻️

#15 Feature/logout
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/HomeFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostDetailActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SettingFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/UserDetailActivity.kt
  PittaSNSApp/app/src/main/res/values-en-rUS/strings.xml
  PittaSNSApp/app/src/main/res/values/strings.xml
Labels: feature ⚙️, fix 🔧

#16 Dev
  PittaSNSApp/.idea/gradle.xml
  PittaSNSApp/app/src/main/AndroidManifest.xml
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/HomeFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/Key.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/MainActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostAddActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostDetailActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/PostUpdateActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SampleData.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SearchFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SettingFragment.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SignInActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/SignUpActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/UserDetailActivity.kt
  PittaSNSApp/app/src/main/java/com/team8/pittasnsapp/UserFragment.kt
  PittaSNSApp/app/src/main/res/drawable/baseline_add_24.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_delete_24.xml
  PittaSNSApp/app/src/main/res/drawable/baseline_edit_24.xml
  PittaSNSApp/app/src/main/res/layout/activity_main.xml
  PittaSNSApp/app/src/main/res/layout/activity_post_add.xml
  PittaSNSApp/app/src/main/res/layout/activity_post_detail.xml
  PittaSNSApp/app/src/main/res/layout/activity_post_update.xml
  PittaSNSApp/app/src/main/res/layout/activity_sign_in.xml
  PittaSNSApp/app/src/main/res/layout/activity_sign_up.xml
  PittaSNSApp/app/src/main/res/layout/activity_user_detail.xml
  PittaSNSApp/app/src/main/res/layout/fragment_user.xml
  PittaSNSApp/app/src/main/res/menu/bottom_memu.xml
  PittaSNSApp/app/src/main/res/menu/toolbar_menu.xml
  PittaSNSApp/app/src/main/res/values-en-rUS/strings.xml
  PittaSNSApp/app/src/main/res/values/strings.xml
Labels: merge ✅
